Repository LikeLion-at-DGU/2025-hackathon-5-simbatda-frontend, pull requests merged in 2025-08, with the labels that each got.

#4 feat: input 공통 컴포넌트
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/toggle/visibility-off.svg
  src/assets/icons/toggle/visibility-on.svg
  src/components/common/input/Input.jsx
  src/components/common/input/Input.styles.js
  src/main.jsx
  src/pages/auth/LoginPage.jsx
  src/pages/auth/SignupPage.jsx
  src/pages/common/TestPage.jsx
  src/router.js
  src/router.jsx
  src/styles/global.css
Labels: feat, 지연

#15 bug: 파일 확장자 추가
  src/router.jsx
Labels: bug, 지연

#16 fix: Netlify 배포 오류 해결 - 파일 확장자 일관성 및 Vite 설정 최적화
  netlify.toml
  src/router.jsx
  vite.config.js
Labels: fix, 지연

#34 고객 페이지 구현
  src/App.jsx
  src/assets/icons/check.svg
  src/assets/icons/uncheck.svg
  src/assets/images/crying-character.svg
  src/assets/images/modal-logo.svg
  src/components/common/card/ProductCard.jsx
  src/components/common/card/ProductCard.styles.js
  src/components/common/header/Header.jsx
  src/components/common/header/Header.styles.js
  src/components/common/modal/OrderAcceptanceModal.jsx
  src/components/common/modal/OrderAcceptanceModal.styles.js
  src/components/common/products/ProductListPage.jsx
  src/components/common/products/ProductListPage.styles.js
  src/components/common/searchbar/SearchBar.jsx
  src/contexts/OrderAcceptanceContext.jsx
  src/mocks/UnifiedMockData.js
  src/pages/main/CustomerOrderDetail.jsx
  src/pages/main/CustomerOrderDetail.styles.js
  src/pages/main/MainPage.jsx
  src/pages/main/OrderHistory.jsx
  src/pages/main/OrderHistory.styles.js
  src/pages/main/ProductRegister.jsx
  src/pages/main/Registeration.jsx
  src/pages/main/Registeration.styles.js
  src/pages/products/RecommendedPage.jsx
  src/pages/products/SpecialPricePage.jsx
  src/pages/store/StoreDetail.jsx
  src/pages/store/StoreDetail.styles.js
  src/router.jsx
  src/styles/global.css
Labels: fix, feat, 지연

#48 api 연결 오류 해결
  src/components/common/bottomsheet/BottomSheet.jsx
  src/components/common/header/BackHeader.styles.js
  src/components/common/modal/OrderAcceptanceModal.jsx
  src/components/common/searchbar/SearchBar.jsx
  src/contexts/OrderAcceptanceContext.jsx
  src/pages/inventory/InventoryMapPage.jsx
  src/pages/main/CustomerOrderDetail.styles.js
  src/pages/main/MainPage.jsx
  src/pages/main/Registeration.jsx
  src/pages/main/Registeration.styles.js
Labels: bug, fix, feat, 지연

#50 fix: homeredirect add
  src/components/common/HomeRedirect.jsx
  src/components/common/header/HeaderSeller.jsx
  src/pages/common/Splash.styles.js
  src/pages/main/WishList.jsx
  src/router.jsx
Labels: fix, feat, 원

#51 bug: 지도 관련 오류 해결
  src/api/products.js
  src/contexts/OrderAcceptanceContext.jsx
  src/pages/inventory/InventoryMapPage.jsx
  src/pages/main/CustomerOrderDetail.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/Registeration.jsx
  src/pages/products/RecommendedPage.jsx
  src/pages/store/StoreDetail.jsx
Labels: bug, fix, 지연, chore

#52 fix: signup, signin페이지 문구 수정
  src/components/common/header/WishListHeader.jsx
  src/pages/auth/Signin.jsx
  src/pages/auth/Signup.jsx
  src/pages/common/ErrorPage.jsx
  src/pages/common/TestPage.jsx
  src/pages/main/MainPageSeller.styles.js
  src/pages/main/OrderDetail.styles.js
  src/router.jsx
Labels: fix, 원, chore, priority: low

#53 fix: 소비자 디자인 수정
  src/assets/icons/active-pin.svg
  src/assets/icons/current-pin.svg
  src/assets/icons/inactive-pin.svg
  src/assets/icons/starsquirrel.svg
  src/components/common/header/BackHeader.styles.js
  src/components/common/header/Header.jsx
  src/components/common/map/AdvancedGoogleMap.jsx
  src/components/common/products/ProductListPage.styles.js
  src/components/common/searchbar/SearckBar.styles.js
  src/pages/inventory/InventoryMapPage.jsx
  src/pages/main/CustomerOrderDetail.styles.js
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.styles.js
  src/pages/main/OrderHistory.jsx
  src/pages/main/OrderHistory.styles.js
  src/pages/main/Registeration.jsx
  src/pages/main/Registeration.styles.js
  src/pages/main/WishList.jsx
  src/pages/store/StoreDetail.styles.js
  src/styles/global.css
Labels: fix, 지연

#54 fix: svg 파일 변경
  src/assets/icons/Bill.png
  src/assets/icons/Bill.svg
  src/assets/icons/Discount.png
  src/assets/icons/Discount.svg
  src/assets/icons/Favorite.png
  src/assets/icons/Favorite.svg
  src/assets/icons/GoodQuality.png
  src/assets/icons/GoodQuality.svg
  src/assets/icons/Important.png
  src/assets/icons/Important.svg
  src/assets/icons/Location.png
  src/assets/icons/Location.svg
  src/assets/icons/crysquirrel.png
  src/assets/icons/dot.png
  src/assets/icons/forward.png
  src/assets/icons/menu.png
  src/assets/icons/menu.svg
  src/assets/icons/search.png
  src/assets/icons/search.svg
  src/assets/icons/starsquirrel.png
  src/assets/icons/x.png
  src/assets/icons/x.svg
  src/assets/images/acorn2.svg
  src/assets/images/acorn3.svg
  src/components/common/header/BackHeader.jsx
  src/components/common/header/Header.jsx
  src/components/common/header/HeaderSeller.jsx
  src/components/common/map/AdvancedGoogleMap.jsx
  src/components/common/searchbar/SearchBar.jsx
  src/pages/main/MainPageSeller.jsx
  src/pages/main/ProductRegister.jsx
Labels: 원, chore, priority: low

#58 fix: 이미지 최적화
  src/assets/images/text-logo.svg
Labels: fix, 지연

#60 fix: 메타데이터 추가
  index.html
  public/greensquirrel.svg
  src/pages/store/StoreDetail.jsx
Labels: fix, 지연

#62 feat:주문번호 수정
  src/components/order/CompletedCard.jsx
  src/components/order/OrderCard.jsx
  src/components/order/OrderProgressCard.jsx
  src/pages/main/MainPageSeller.jsx
  src/pages/main/OrderCompleted.jsx
  src/pages/main/OrderDetail.jsx
  src/pages/main/OrderInProgress.jsx
Labels: feat, 원

#66 fix: 이미지 최적화
  README.md
  src/assets/icons/active-pin.png
  src/assets/icons/current-pin.png
  src/assets/icons/inactive-pin.png
  src/assets/icons/menu.png
  src/assets/icons/starsquirrel.png
  src/assets/images/002.png
  src/assets/images/003.png
  src/assets/images/004.png
  src/assets/images/005.png
  src/assets/images/text-logo.png
  src/components/common/header/Header.jsx
  src/components/common/header/Header.styles.js
  src/components/common/header/HeaderSeller.jsx
  src/components/common/header/HeaderSeller.styles.js
  src/components/common/map/AdvancedGoogleMap.jsx
  src/pages/main/MainPageSeller.styles.js
Labels: fix, 지연

#67 fix: 디자인 수정
  src/assets/icons/Location.png
  src/assets/icons/dots.png
  src/assets/images/002.png
  src/assets/images/003.png
  src/assets/images/004.png
  src/assets/images/005.png
  src/assets/images/acorn1.png
  src/assets/images/acorns.png
  src/assets/images/greensquirrel.png
  src/assets/images/splashsquirrel.png
  src/assets/images/text-logo-white.png
  src/components/common/map/AdvancedGoogleMap.jsx
  src/components/product/ProductCard.jsx
  src/components/product/ProductCard.styles.js
  src/pages/auth/Signin.jsx
  src/pages/auth/SigninSeller.jsx
  src/pages/auth/Signup.jsx
  src/pages/auth/SignupSeller.jsx
  src/pages/auth/StoreDocumentUpload.jsx
  src/pages/auth/StoreRegistration.jsx
  src/pages/common/Splash.jsx
Labels: fix, 지연
